export const ENDPOINTS = {
  products: '/products',
  productById: (id) => `/products/${id}`,
  categories: '/categories',
  flavours: '/flavours',
  occasions: '/occasions',
  addons: '/addons',
  banners: '/banners/live',
  blog: '/blog/published',
  faqs: '/faqs',
  reviews: '/reviews',
  settings: '/settings',
  newsletter: '/newsletter/subscribe',
  orders: '/orders',
  razorpayOrder: '/payments/razorpay/order',
  myOrders: '/orders/mine',
  myOrderByCode: (code) => `/orders/mine/${encodeURIComponent(code)}`,
  myTransactions: '/transactions/mine',
  changePassword: '/auth/me/password',
  addresses: '/auth/me/addresses',
  addressById: (id) => `/auth/me/addresses/${id}`,
  addressDefault: (id) => `/auth/me/addresses/${id}/default`,
  orderByCode: (code) => `/orders/track/${encodeURIComponent(code)}`,
  enquiries: '/enquiries',
  myEnquiries: '/enquiries/mine',
  login: '/auth/login',
  register: '/auth/register',
  me: '/auth/me',
};
