export const ENDPOINTS = {
  products: '/products',
  productById: (id) => `/products/${id}`,
  categories: '/categories',
  flavours: '/flavours',
  occasions: '/occasions',
  addons: '/addons',
  banners: '/banners/live',
  blog: '/blog/published',
  faqs: '/faqs',
  reviews: '/reviews',
  settings: '/settings',
  newsletter: '/newsletter/subscribe',
  orders: '/orders',
  myOrders: '/orders/mine',
  orderByCode: (code) => `/orders/track/${encodeURIComponent(code)}`,
  enquiries: '/enquiries',
  myEnquiries: '/enquiries/mine',
  login: '/auth/login',
  register: '/auth/register',
  me: '/auth/me',
};
